#!/bin/bash
# YT-Shorts-Block - Linux/macOS Installer
echo "=== YT-Shorts-Block Installer ==="
echo ""
echo "RECOMMENDED: Use the uBlock Origin filter list:"
echo "1. Install uBlock Origin"
echo "2. Open uBlock -> Dashboard -> Filter Lists -> Import"
echo "3. Paste: https://raw.githubusercontent.com/ShoumikBalaSomu/YT-shorts-Block/main/filter-lists/yt-shorts-ublock.txt"
echo "4. Click Apply Changes"
echo ""
echo "For browser extension (maximum protection):"
echo "1. git clone https://github.com/ShoumikBalaSomu/YT-shorts-Block.git"
echo "2. Open chrome://extensions/ -> Enable Developer Mode"
echo "3. Load Unpacked -> select browser-extension/ folder"
echo ""
echo "Done! YouTube Shorts are eliminated."
